<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="User-PC" failures="3" tests="5" name="Sprint1" time="0.242" errors="0" timestamp="2021-03-12T10:29:16 IST">
  <testcase classname="testNgFailTestCase.TestCase5" name="yahooLoginTest" time="0.036"/>
  <testcase classname="testNgFailTestCase.TestCase4" name="radiffLoginTest" time="0.005"/>
  <testcase classname="testNgFailTestCase.TestCase3" name="mercuryLoginTest" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgFailTestCase.TestCase3.mercuryLoginTest(TestCase3.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- mercuryLoginTest -->
  <testcase classname="testNgFailTestCase.TestCase2" name="gmailLoginTest" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgFailTestCase.TestCase2.gmailLoginTest(TestCase2.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- gmailLoginTest -->
  <testcase classname="testNgFailTestCase.TestCase1" name="fbLoginTest" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgFailTestCase.TestCase1.fbLoginTest(TestCase1.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fbLoginTest -->
</testsuite> <!-- Sprint1 -->
